USE [master]
GO

/****** Object:  Database [stefagames]    Script Date: 31/10/2017 14:37:11 ******/
CREATE DATABASE [stefagames]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'stefagames', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\stefagames.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'stefagames_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\stefagames_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [stefagames].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [stefagames] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [stefagames] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [stefagames] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [stefagames] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [stefagames] SET ARITHABORT OFF 
GO

ALTER DATABASE [stefagames] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [stefagames] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [stefagames] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [stefagames] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [stefagames] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [stefagames] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [stefagames] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [stefagames] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [stefagames] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [stefagames] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [stefagames] SET  DISABLE_BROKER 
GO

ALTER DATABASE [stefagames] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [stefagames] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [stefagames] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [stefagames] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [stefagames] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [stefagames] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [stefagames] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [stefagames] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [stefagames] SET  MULTI_USER 
GO

ALTER DATABASE [stefagames] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [stefagames] SET DB_CHAINING OFF 
GO

ALTER DATABASE [stefagames] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [stefagames] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [stefagames] SET  READ_WRITE 
GO

